import { collection, addDoc, Timestamp } from 'firebase/firestore';
import { db } from './firebase';

const DEMO_ISSUES = [
  {
    title: 'Large Pothole Near Maninagar Cross Roads',
    description: 'A deep pothole approximately 2 feet wide has formed near Maninagar cross roads. It has caused two vehicle accidents this week and poses serious risk to two-wheeler riders especially at night.',
    category: 'pothole',
    severity: 'critical',
    suggestedAuthority: 'Municipal Corporation',
    location: { lat: 23.0035, lng: 72.6012, address: 'Maninagar Cross Roads, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/pothole.jpg',
    status: 'verified',
    verificationCount: 7,
    upvotes: ['user1','user2','user3','user4','user5','user6','user7'],
  },
  {
    title: 'Street Light Not Working on SG Highway',
    description: 'Three consecutive street lights on SG Highway near Bodakdev are non-functional for the past 10 days. The dark stretch is causing safety concerns for pedestrians and late-night commuters.',
    category: 'streetlight',
    severity: 'high',
    suggestedAuthority: 'Electricity Board',
    location: { lat: 23.0469, lng: 72.5060, address: 'SG Highway, Bodakdev, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/streetlight.jpg',
    status: 'reported',
    verificationCount: 4,
    upvotes: ['user1','user2','user3','user4'],
  },
  {
    title: 'Garbage Overflowing Near Satellite Market',
    description: 'The municipal garbage bin near Satellite market has not been cleared in 5 days. Waste is overflowing onto the footpath creating unhygienic conditions and foul smell affecting nearby shops and residents.',
    category: 'garbage',
    severity: 'high',
    suggestedAuthority: 'Sanitation Department',
    location: { lat: 23.0300, lng: 72.5100, address: 'Satellite Market, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/garbage.jpg',
    status: 'verified',
    verificationCount: 12,
    upvotes: ['user1','user2','user3','user4','user5','user6','user7','user8','user9','user10','user11','user12'],
  },
  {
    title: 'Water Pipeline Leakage in Navrangpura',
    description: 'A municipal water pipeline has been leaking near Navrangpura for 3 days resulting in water wastage and road damage. The water is seeping into the road causing the surface to weaken.',
    category: 'water',
    severity: 'high',
    suggestedAuthority: 'Water Board',
    location: { lat: 23.0450, lng: 72.5603, address: 'Navrangpura, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/water.jpg',
    status: 'in_progress',
    verificationCount: 5,
    upvotes: ['user1','user2','user3','user4','user5'],
  },
  {
    title: 'Blocked Drainage Causing Waterlogging in Bopal',
    description: 'The storm drainage near Bopal circle is completely blocked with debris causing severe waterlogging during even light rainfall. Residents are unable to exit their homes during rain.',
    category: 'drainage',
    severity: 'critical',
    suggestedAuthority: 'Municipal Corporation',
    location: { lat: 23.0156, lng: 72.4695, address: 'Bopal Circle, Bopal, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/drainage.jpg',
    status: 'reported',
    verificationCount: 9,
    upvotes: ['user1','user2','user3','user4','user5','user6','user7','user8','user9'],
  },
  {
    title: 'Pothole Damaging Vehicles Near Vastrapur Lake',
    description: 'Multiple potholes have formed on the road adjacent to Vastrapur Lake. The road surface has completely deteriorated with several potholes causing damage to vehicles and creating traffic slowdowns.',
    category: 'pothole',
    severity: 'medium',
    suggestedAuthority: 'PWD',
    location: { lat: 23.0388, lng: 72.5280, address: 'Vastrapur Lake Road, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/pothole2.jpg',
    status: 'reported',
    verificationCount: 3,
    upvotes: ['user1','user2','user3'],
  },
  {
    title: 'Broken Street Light at Paldi Junction',
    description: 'The street light at Paldi junction has a broken fixture hanging loose from the pole. It poses an electrical hazard especially during rain and the dangling wire is a safety risk to passersby.',
    category: 'streetlight',
    severity: 'critical',
    suggestedAuthority: 'Electricity Board',
    location: { lat: 23.0168, lng: 72.5714, address: 'Paldi Junction, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/streetlight2.jpg',
    status: 'verified',
    verificationCount: 6,
    upvotes: ['user1','user2','user3','user4','user5','user6'],
  },
  {
    title: 'Illegal Garbage Dumping Near Thaltej',
    description: 'An unauthorized garbage dump has formed on the vacant plot near Thaltej road. Construction debris and household waste is being dumped illegally creating a health hazard for the entire neighborhood.',
    category: 'garbage',
    severity: 'medium',
    suggestedAuthority: 'Sanitation Department',
    location: { lat: 23.0587, lng: 72.5068, address: 'Thaltej Road, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/garbage2.jpg',
    status: 'resolved',
    verificationCount: 8,
    upvotes: ['user1','user2','user3','user4','user5','user6','user7','user8'],
  },
  {
    title: 'Water Supply Disruption in Gota Area',
    description: 'Residents of Gota sector 6 have not received municipal water supply for 2 days. The main supply line appears to have a fault and multiple households are affected forcing people to buy water.',
    category: 'water',
    severity: 'medium',
    suggestedAuthority: 'Water Board',
    location: { lat: 23.1021, lng: 72.5162, address: 'Gota Sector 6, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/water2.jpg',
    status: 'reported',
    verificationCount: 2,
    upvotes: ['user1','user2'],
  },
  {
    title: 'Overflowing Manhole on CG Road',
    description: 'A manhole on CG Road near Panjarapole is overflowing with sewage water spilling onto the road. The foul smell and contamination risk is affecting pedestrians and nearby restaurants.',
    category: 'drainage',
    severity: 'high',
    suggestedAuthority: 'Municipal Corporation',
    location: { lat: 23.0395, lng: 72.5603, address: 'CG Road, Panjarapole, Ahmedabad, Gujarat', city: 'Ahmedabad' },
    photoURL: 'https://i.ibb.co/placeholder/drainage2.jpg',
    status: 'verified',
    verificationCount: 11,
    upvotes: ['user1','user2','user3','user4','user5','user6','user7','user8','user9','user10','user11'],
  },
];

export const seedIssues = async (userId: string): Promise<void> => {
  const now = Timestamp.now();
  for (const issue of DEMO_ISSUES) {
    await addDoc(collection(db, 'issues'), {
      ...issue,
      aiConfidence: 0.9,
      reportedBy: userId,
      reportedAt: now,
      updatedAt: now,
      timeline: [
        {
          status: 'reported',
          timestamp: now,
          note: 'Issue reported by citizen',
        },
      ],
    });
  }
  console.log('✅ Seeded 10 demo issues');
};
